
import { MarineLife } from './types';

export const MOCK_MARINE_LIFE: MarineLife[] = [
  {
    id: 'lionfish',
    name: '狮子鱼 (Lionfish)',
    scientificName: 'Pterois',
    isPoisonous: true,
    description: '具有极具观赏性的条纹，但其背鳍鳍条有剧毒。',
    toxicityLevel: 8,
    behaviorTip: '切勿触摸，应保持至少3米距离。',
    imageUrl: 'https://picsum.photos/seed/lionfish/400/300'
  },
  {
    id: 'clownfish',
    name: '小丑鱼 (Clownfish)',
    scientificName: 'Amphiprioninae',
    isPoisonous: false,
    description: '常与海葵共生，对潜水员非常友好。',
    behaviorTip: '观察它们在海葵中的穿梭，不要惊扰海葵。',
    imageUrl: 'https://picsum.photos/seed/clown/400/300'
  },
  {
    id: 'sea_snake',
    name: '海蛇 (Sea Snake)',
    scientificName: 'Hydrophiinae',
    isPoisonous: true,
    description: '剧毒生物，虽通常性格温顺，但咬伤致命。',
    toxicityLevel: 10,
    behaviorTip: '发现后应缓慢向后退，不要有剧烈动作。',
    imageUrl: 'https://picsum.photos/seed/snake/400/300'
  },
  {
    id: 'turtle',
    name: '绿海龟 (Green Sea Turtle)',
    scientificName: 'Chelonia mydas',
    isPoisonous: false,
    description: '优雅的长寿爬行动物，以海草为食。',
    behaviorTip: '跟随它们的节奏游泳，避免遮挡其上浮换气的路径。',
    imageUrl: 'https://picsum.photos/seed/turtle/400/300'
  }
];

export const SEA_AREAS = [
  { id: 'scs', nameZh: '南海 - 西沙群岛', nameEn: 'South China Sea - Xisha Islands', lat: 16.8, lng: 112.3, fishCount: 450, imageUrl: '/sea_areas/south_china_sea.png' },
  { id: 'sanya', nameZh: '三亚 - 蜈支洲岛', nameEn: 'Sanya - Wuzhizhou Island', lat: 18.2, lng: 109.5, fishCount: 320, imageUrl: '/sea_areas/sanya.png' },
  { id: 'philippines', nameZh: '菲律宾 - 薄荷岛', nameEn: 'Philippines - Bohol Island', lat: 9.6, lng: 123.8, fishCount: 600, imageUrl: '/sea_areas/philippines.png' }
];

// src/constants.ts
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  zh: {
    nav_home: '首页',
    nav_community: '社区',
    nav_dive: '潜水',
    nav_log: '日志',
    nav_me: '个人',
    hub_title: 'OceanEyes',
    hub_subtitle: 'AI 水下智能助手',
    search_placeholder: '搜索海域或鱼类...',
    current_location: '当前位置',
    gps_on: '定位已开启',
    fish_directory: '分布生物科普',
    view_all: '查看全部',
    poisonous: '有毒',
    dive_ready: '已准备就绪',
    dive_ready_desc: '连接运动相机 (GoPro) 和智能眼镜后，点击开始潜水进行实时目标检测。',
    start_diving: '进入潜水模式',
    end_dive: '结束本次潜水',
    safety_shield: '安全护航中',
    emergency_warning: '紧急：附近发现有毒生物',
    report_title: '潜水战报分析',
    dive_time: '潜水时长',
    species_count: '发现种类',
    safety_alert_title: '危险识别报警',
    safety_alert_desc: '系统在本场潜水中识别到 {count} 次有毒生物接近。',
    ai_summary_title: 'Gemini 3 智能综述',
    ai_highlights_title: 'AI 截取精彩瞬间',
    community_title: '发现社区',
    filter_all: '全部',
    filter_area: '按海域',
    filter_toxic: '有毒生物',
    filter_ai: 'AI精选',
    filter_photo: '摄影作品',
    follow: '关注',
    settings_title: '应用设置',
    lang_settings: '语言设置 / Language',
    device_mgmt: '设备管理',
    rescan: '重新扫描',
    scanning: '扫描中...',
    glasses: '智能眼镜 (AR Glasses)',
    connected: '已连接',
    disconnected: '未连接',
    pairing: '配对',
    model_update: '离线识别模型更新',
    logout: '退出登录',
    // 新增：鱼类识别中文翻译
    dive_title: '水下探索模式',
    dive_subtitle: '红框=有毒鱼 · 白框=无毒鱼 | 点击识别后查看结果',
    camera: '摄像头',
    local_video: '本地视频',
    tap_open_camera: '点击下方按钮打开摄像头',
    tap_upload_video: '点击上传潜水视频',
    open_camera: '打开摄像头',
    start_record: '开始录制',
    stop_record: '停止录制',
    recording: '录制中',
    start_detect: '开始探索',
    processing: '识别中...',
    detect_result: '识别结果',
    end_explore: '结束探索 · 查看报告',
    camera_error: '无法访问摄像头，请检查权限/设备',
    file_error: '请选择有效的视频文件（MP4/AVI/MOV）',
    no_file: '请先选择本地视频文件',
    no_record: '请先录制摄像头视频',
    network_error: '网络错误，请检查后端是否启动',
    record_done: '录制完成，可点击开始探索',
    fish_guide_title: '鱼类科普',
    species_frequency: '发现种类频次',
    fish_toxic_tag: '有毒/需注意',
    fish_safe_tip: '观察建议',
  },
  en: {
    nav_home: 'Home',
    nav_community: 'Social',
    nav_dive: 'Dive',
    nav_log: 'Log',
    nav_me: 'Me',
    hub_title: 'OceanEyes',
    hub_subtitle: 'AI Underwater Hub',
    search_placeholder: 'Search areas or fish...',
    current_location: 'Location',
    gps_on: 'GPS ACTIVE',
    fish_directory: 'Marine Life Catalog',
    view_all: 'All',
    poisonous: 'TOXIC',
    dive_ready: 'SYSTEM READY',
    dive_ready_desc: 'Connect your Action Cam and Smart Glasses to enable real-time detection.',
    start_diving: 'START DIVING',
    end_dive: 'END SESSION',
    safety_shield: 'SHIELD ACTIVE',
    emergency_warning: 'EMERGENCY: TOXIC ORGANISM NEARBY',
    report_title: 'Dive Session Report',
    dive_time: 'Duration',
    species_count: 'Species Found',
    safety_alert_title: 'SAFETY ALERT',
    safety_alert_desc: 'Identified {count} toxic threats during this dive.',
    ai_summary_title: 'Gemini 3 Insights',
    ai_highlights_title: 'AI Video Highlights',
    community_title: 'Community',
    filter_all: 'All',
    filter_area: 'By Area',
    filter_toxic: 'Toxic Only',
    filter_ai: 'AI Picks',
    filter_photo: 'Gallery',
    follow: 'Follow',
    settings_title: 'App Settings',
    lang_settings: 'Language Settings',
    device_mgmt: 'Device Management',
    rescan: 'Re-scan',
    scanning: 'Scanning...',
    camera: 'Camera',
    glasses: 'AR Glasses',
    connected: 'Connected',
    disconnected: 'Disconnected',
    pairing: 'Pair',
    model_update: 'Model Updates',
    logout: 'Logout',
    dive_title: 'Underwater Exploration',
    dive_subtitle: 'Red=Toxic · White=Safe | Tap to detect',
    local_video: 'Local Video',
    tap_open_camera: 'Tap to open camera',
    tap_upload_video: 'Tap to upload dive video',
    open_camera: 'Open Camera',
    start_record: 'Start Record',
    stop_record: 'Stop Record',
    recording: 'Recording',
    start_detect: 'Start Explore',
    processing: 'Detecting...',
    detect_result: 'Detect Result',
    end_explore: 'End Explore · View Report',
    camera_error: 'Cannot access camera, check permissions',
    file_error: 'Please select a valid video file',
    no_file: 'Please select a local video first',
    no_record: 'Please record a camera video first',
    network_error: 'Network error, check backend',
    record_done: 'Record done, tap to explore',
    fish_guide_title: 'Fish Species Guide',
    species_frequency: 'Species Encounter Frequency',
    fish_toxic_tag: 'Toxic',
    fish_safe_tip: 'Observation Tip',
  }
};
