/**
 * 鱼类百科：YOLO 模型 class_id 到鱼类科普内容的映射
 * 对应 data.yaml 中的 26 个类别
 */
export interface FishEntry {
  id: number;
  nameZh: string;
  nameEn: string;
  scientificName: string;
  descriptionZh: string;
  descriptionEn: string;
  isToxic: boolean;
  behaviorTipZh: string;
  behaviorTipEn: string;
}

export const FISH_ENCYCLOPEDIA: Record<number, FishEntry> = {
  0: {
    id: 0,
    nameZh: '刺尾鱼',
    nameEn: 'Surgeonfish',
    scientificName: 'Acanthuridae',
    descriptionZh: '刺尾鱼科鱼类，尾柄两侧有可竖起的尖锐骨刺，用于防卫。多栖息于珊瑚礁区，以藻类为食。部分种类皮肤黏液含毒素。',
    descriptionEn: 'Surgeonfishes have sharp scalpels on their tail peduncle for defense. They graze on algae in coral reefs.',
    isToxic: true,
    behaviorTipZh: '避免触碰尾柄骨刺，保持适当观赏距离。',
    behaviorTipEn: 'Avoid touching the caudal spine; maintain a safe viewing distance.',
  },
  1: {
    id: 1,
    nameZh: '扳机鱼',
    nameEn: 'Triggerfish',
    scientificName: 'Balistidae',
    descriptionZh: '扳机鱼科，性情凶猛，繁殖期具有强烈领地意识，会主动攻击靠近的潜水员。肉食性，部分种类含有雪卡毒素。',
    descriptionEn: 'Triggerfishes are aggressive during breeding and may attack divers. Some carry ciguatera toxin.',
    isToxic: true,
    behaviorTipZh: '繁殖季远离巢穴，遇攻击缓慢后退勿激怒。',
    behaviorTipEn: 'Stay away from nests during breeding season; retreat slowly if charged.',
  },
  2: {
    id: 2,
    nameZh: '鲹',
    nameEn: 'Jack',
    scientificName: 'Carangidae',
    descriptionZh: '鲹科鱼类，体侧扁，游速快，常成群活动。多分布于热带和亚热带海域，为重要经济鱼类。',
    descriptionEn: 'Jacks are streamlined, fast-swimming fish often seen in schools in tropical waters.',
    isToxic: false,
    behaviorTipZh: '可安全观赏，注意勿阻挡鱼群游动路线。',
    behaviorTipEn: 'Safe to observe; avoid blocking school movement.',
  },
  3: {
    id: 3,
    nameZh: '白鲳',
    nameEn: 'Spadefish',
    scientificName: 'Ephippidae',
    descriptionZh: '白鲳科，体圆扁，黑白条纹显著。常成群在礁石附近活动，性情温和，对潜水员好奇。',
    descriptionEn: 'Spadefishes have distinctive black and white stripes and are curious around divers.',
    isToxic: false,
    behaviorTipZh: '性情温和，可静待其靠近观察。',
    behaviorTipEn: 'Gentle fish; wait for them to approach for observation.',
  },
  4: {
    id: 4,
    nameZh: '隆头鱼',
    nameEn: 'Wrasse',
    scientificName: 'Labridae',
    descriptionZh: '隆头鱼科，种类繁多，色彩鲜艳。多为日行性，夜眠于沙中。部分种类具性逆转现象。',
    descriptionEn: 'Wrasses are colorful, diurnal fish; some bury themselves in sand at night.',
    isToxic: false,
    behaviorTipZh: '可安全观赏，夜间勿惊扰沙中休眠个体。',
    behaviorTipEn: 'Safe to observe; avoid disturbing sleeping fish at night.',
  },
  5: {
    id: 5,
    nameZh: '笛鲷',
    nameEn: 'Snapper',
    scientificName: 'Lutjanidae',
    descriptionZh: '笛鲷科，体侧扁，多为红色系。群聚或独居，栖息于礁石及沙泥底。部分大型种类含雪卡毒。',
    descriptionEn: 'Snappers are reddish reef fish; some large species may carry ciguatera.',
    isToxic: false,
    behaviorTipZh: '观赏安全，食用需注意大型个体可能有毒。',
    behaviorTipEn: 'Safe to observe; large individuals may be toxic if consumed.',
  },
  6: {
    id: 6,
    nameZh: '神仙鱼',
    nameEn: 'Angelfish',
    scientificName: 'Pomacanthidae',
    descriptionZh: '神仙鱼科，体侧扁，体色艳丽。多独居或成对，以海绵、藻类为食。幼鱼与成鱼体色差异大。',
    descriptionEn: 'Angelfishes are brightly colored; juveniles often look different from adults.',
    isToxic: false,
    behaviorTipZh: '性情温和，可近距离观赏。',
    behaviorTipEn: 'Gentle species; good for close observation.',
  },
  7: {
    id: 7,
    nameZh: '雀鲷',
    nameEn: 'Damselfish',
    scientificName: 'Pomacentridae',
    descriptionZh: '雀鲷科，体型小，色彩丰富。常与海葵共生（如小丑鱼），具强烈领地性，会驱赶入侵者。',
    descriptionEn: 'Damselfishes are small, territorial; clownfish live in symbiosis with anemones.',
    isToxic: false,
    behaviorTipZh: '领地意识强，勿伸手入其巢穴。',
    behaviorTipEn: 'Highly territorial; avoid reaching into their nests.',
  },
  8: {
    id: 8,
    nameZh: '鹦嘴鱼',
    nameEn: 'Parrotfish',
    scientificName: 'Scaridae',
    descriptionZh: '鹦嘴鱼科，喙状齿可啃食珊瑚。日间觅食，夜间分泌黏液裹身睡眠。对珊瑚礁生态平衡重要。',
    descriptionEn: 'Parrotfishes graze on coral; they secrete mucus cocoons to sleep at night.',
    isToxic: false,
    behaviorTipZh: '可安全观赏，勿惊扰夜间裹膜休眠的个体。',
    behaviorTipEn: 'Safe to observe; avoid disturbing sleeping individuals at night.',
  },
  9: {
    id: 9,
    nameZh: '金枪鱼',
    nameEn: 'Tuna',
    scientificName: 'Scombridae',
    descriptionZh: '鲭科金枪鱼类，游速极快，大洋性洄游鱼类。体型大，为重要经济鱼种。',
    descriptionEn: 'Tunas are fast, oceanic migrants; important commercially.',
    isToxic: false,
    behaviorTipZh: '通常远洋活动，偶遇可远观。',
    behaviorTipEn: 'Usually in open water; observe from a distance if encountered.',
  },
  10: {
    id: 10,
    nameZh: '石斑鱼',
    nameEn: 'Grouper',
    scientificName: 'Serranidae',
    descriptionZh: '石斑鱼科，体型大，多栖于礁洞。肉食性，性情相对温和。部分种类可与人互动。',
    descriptionEn: 'Groupers are large, often found in caves; carnivorous but generally docile.',
    isToxic: false,
    behaviorTipZh: '大型个体勿挑衅，保持尊重距离。',
    behaviorTipEn: 'Give large individuals space; do not provoke.',
  },
  11: {
    id: 11,
    nameZh: '鲨鱼',
    nameEn: 'Shark',
    scientificName: 'Selachimorpha',
    descriptionZh: '软骨鱼类，顶级掠食者。多数种类不主动攻击人类，但对血腥和快速动作敏感。',
    descriptionEn: 'Sharks are apex predators; most do not attack humans but may react to blood or sudden movement.',
    isToxic: false,
    behaviorTipZh: '保持镇定，避免剧烈动作，勿背对鲨鱼快速游动。',
    behaviorTipEn: 'Stay calm; avoid sudden movements; do not turn your back and swim away quickly.',
  },
  12: {
    id: 12,
    nameZh: '角镰鱼',
    nameEn: 'Moorish Idol',
    scientificName: 'Zanclidae',
    descriptionZh: '角镰鱼科，体黄黑白三色，背鳍延长如丝带。独居或小群，以海绵、藻类为食。',
    descriptionEn: 'Moorish idols have distinctive coloration and elongated dorsal fins.',
    isToxic: false,
    behaviorTipZh: '性情温和，可安全观赏。',
    behaviorTipEn: 'Gentle fish; safe to observe.',
  },
  13: {
    id: 13,
    nameZh: '角镰鱼',
    nameEn: 'Moorish Idol',
    scientificName: 'Zanclidae',
    descriptionZh: '角镰鱼科（同义类别），体色鲜艳，背鳍飘逸。',
    descriptionEn: 'Moorish idols - same family as class 12.',
    isToxic: false,
    behaviorTipZh: '可安全观赏。',
    behaviorTipEn: 'Safe to observe.',
  },
  14: {
    id: 14,
    nameZh: '神仙鱼',
    nameEn: 'Angel',
    scientificName: 'Pomacanthidae',
    descriptionZh: '神仙鱼（简名），体色艳丽，多栖于珊瑚礁。',
    descriptionEn: 'Angel fish - reef dwellers with bright colors.',
    isToxic: false,
    behaviorTipZh: '可安全观赏。',
    behaviorTipEn: 'Safe to observe.',
  },
  15: {
    id: 15,
    nameZh: '雀鲷',
    nameEn: 'Damsel',
    scientificName: 'Pomacentridae',
    descriptionZh: '雀鲷（简名），领地性强，色彩丰富。',
    descriptionEn: 'Damsel fish - territorial and colorful.',
    isToxic: false,
    behaviorTipZh: '勿侵入其领地进行挑衅。',
    behaviorTipEn: 'Avoid invading their territory.',
  },
  16: {
    id: 16,
    nameZh: '石斑鱼',
    nameEn: 'Grouper',
    scientificName: 'Serranidae',
    descriptionZh: '石斑鱼（简名），大型底栖肉食鱼。',
    descriptionEn: 'Grouper - large benthic carnivore.',
    isToxic: false,
    behaviorTipZh: '保持尊重距离。',
    behaviorTipEn: 'Maintain respectful distance.',
  },
  17: {
    id: 17,
    nameZh: '鲹',
    nameEn: 'Jack',
    scientificName: 'Carangidae',
    descriptionZh: '鲹（简名），快速游动的群居鱼类。',
    descriptionEn: 'Jack - fast schooling fish.',
    isToxic: false,
    behaviorTipZh: '可安全观赏。',
    behaviorTipEn: 'Safe to observe.',
  },
  18: {
    id: 18,
    nameZh: '鹦嘴鱼',
    nameEn: 'Parrot',
    scientificName: 'Scaridae',
    descriptionZh: '鹦嘴鱼（简名），啃食珊瑚的礁区鱼。',
    descriptionEn: 'Parrotfish - coral grazers.',
    isToxic: false,
    behaviorTipZh: '可安全观赏。',
    behaviorTipEn: 'Safe to observe.',
  },
  19: {
    id: 19,
    nameZh: '鲨鱼',
    nameEn: 'Shark',
    scientificName: 'Selachimorpha',
    descriptionZh: '鲨鱼（简名），顶级掠食者。',
    descriptionEn: 'Shark - apex predator.',
    isToxic: false,
    behaviorTipZh: '保持镇定，勿剧烈动作。',
    behaviorTipEn: 'Stay calm; avoid sudden movements.',
  },
  20: {
    id: 20,
    nameZh: '笛鲷',
    nameEn: 'Snapper',
    scientificName: 'Lutjanidae',
    descriptionZh: '笛鲷（简名），红色系礁鱼。',
    descriptionEn: 'Snapper - reddish reef fish.',
    isToxic: false,
    behaviorTipZh: '可安全观赏。',
    behaviorTipEn: 'Safe to observe.',
  },
  21: {
    id: 21,
    nameZh: '白鲳',
    nameEn: 'Spade',
    scientificName: 'Ephippidae',
    descriptionZh: '白鲳（简名），黑白条纹显著。',
    descriptionEn: 'Spadefish - black and white striped.',
    isToxic: false,
    behaviorTipZh: '可安全观赏。',
    behaviorTipEn: 'Safe to observe.',
  },
  22: {
    id: 22,
    nameZh: '刺尾鱼',
    nameEn: 'Surgeon',
    scientificName: 'Acanthuridae',
    descriptionZh: '刺尾鱼（简名），尾柄具骨刺，部分含毒。',
    descriptionEn: 'Surgeonfish - caudal spine; some species toxic.',
    isToxic: true,
    behaviorTipZh: '避免触碰尾柄骨刺。',
    behaviorTipEn: 'Avoid touching the caudal spine.',
  },
  23: {
    id: 23,
    nameZh: '扳机鱼',
    nameEn: 'Trigger',
    scientificName: 'Balistidae',
    descriptionZh: '扳机鱼（简名），繁殖期具攻击性。',
    descriptionEn: 'Triggerfish - aggressive during breeding.',
    isToxic: true,
    behaviorTipZh: '繁殖季远离巢穴。',
    behaviorTipEn: 'Stay away from nests during breeding.',
  },
  24: {
    id: 24,
    nameZh: '金枪鱼',
    nameEn: 'Tuna',
    scientificName: 'Scombridae',
    descriptionZh: '金枪鱼（简名），大洋快速游泳者。',
    descriptionEn: 'Tuna - oceanic speed swimmer.',
    isToxic: false,
    behaviorTipZh: '可远观。',
    behaviorTipEn: 'Observe from distance.',
  },
  25: {
    id: 25,
    nameZh: '隆头鱼',
    nameEn: 'Wrasse',
    scientificName: 'Labridae',
    descriptionZh: '隆头鱼（简名），色彩鲜艳的日行鱼。',
    descriptionEn: 'Wrasse - colorful diurnal fish.',
    isToxic: false,
    behaviorTipZh: '可安全观赏。',
    behaviorTipEn: 'Safe to observe.',
  },
};
